apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # CHANGE_YOUR_EMAIL_HERE
    email: ricardo.oliveira@awnet.com.br
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
